# cargo-features = ["rename-dependency"]

[package]
edition = "2018"
name = "futures-test"
version = "0.1.0"
authors = ["redtankd <redtankd@qq.com>"]

[lib]
name = "futures_test"

[dependencies]
futures-preview = "0.3.0-alpha.17"
tokio = "0.2.0-alpha.1"
timer = "0.2"
chrono = "0.4"
