sudo: false

language: rust

rust:
  - stable
  # - beta
  # - nightly

env:
  global:
    - LOCAL="~/.local"  # install here to avoid `sudo`
  matrix:
    - TEST_DIR="code-coverage"
    - TEST_DIR="syntax"
    - TEST_DIR="async/futures"
    - TEST_DIR="database/diesel"
    - TEST_DIR="database/postgres"

services:
  - postgresql

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      #- libiberty-dev # <- no such thing in Ubuntu 12.04
      - g++

install:
    - export PATH=$LOCAL/bin:$HOME/.cargo/bin:$PATH
    - mkdir -p $LOCAL/bin
    - mkdir -p ~/.cargo/bin

    # 1. Install kcov
    - export SRC_DIR_KCOV=~/kcov-src
    - export URL_GIT_KCOV=https://github.com/SimonKagstrom/kcov.git
    - |
        git clone $URL_GIT_KCOV $SRC_DIR_KCOV
        cd $SRC_DIR_KCOV

        # default to latest tagged version
        DEFAULT_KCOV_GIT_REF=$(git tag --list | grep "^v[0-9]\+$" | sort -V | tail --lines 1)
        KCOV_GIT_REF=${KCOV_GIT_REF:-$DEFAULT_KCOV_GIT_REF}
        git reset --hard $KCOV_GIT_REF;

        cd $SRC_DIR_KCOV && 
          mkdir build && 
          cd build && 
          cmake -DCMAKE_INSTALL_PREFIX=$LOCAL .. && 
          make && 
          make install
    - cd $TRAVIS_BUILD_DIR

    # 2. Install cargo-kcov.
    - cargo install cargo-kcov

before_script:
  - export RUSTFLAGS="-C link-dead-code"
  - cd $TRAVIS_BUILD_DIR
  - cd $TEST_DIR
  - |
      if [ "${TEST_DIR:0:8}" = "database" ]; then 
        psql -h localhost -U postgres -c "create user diesel createdb password 'diesel'"
        psql -h localhost -U postgres -c "create database diesel with owner diesel"
      fi
  - |
      if [ "$TEST_DIR" = "database/diesel" ]; then
        cargo install diesel_cli
        diesel migration run
      fi


after_success: |
  cargo kcov --verbose -- --verify --coveralls-id=$TRAVIS_JOB_ID \
    --strip-path=$TRAVIS_BUILD_DIR \
    --exclude-pattern=/.cargo,target \
    --exclude-region='#[cfg(test)]://[cfg(test)]'
    