# Partner Queue Solution, which can be used completely for free.
# https://docs.travis-ci.com/user/billing-overview/#partner-queue-solution
os: linux

arch:
  - arm64

# the default dist doesn't support grcov, so ubuntu 20.4 is used.
dist: focal

language: rust

addons:
  apt:
    packages:
      - unzip
  hosts:
    # Custom Host Names for database demos' connection string in `.env` file. It is the same as localhost.
    - postgres

services:
  - postgresql

env:
  global:
    # apps deployed here to avoid `sudo`
    - PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH
    #
    # source-based coverage
    - RUSTFLAGS="-Cinstrument-coverage"
    - LLVM_PROFILE_FILE="coverage-%p-%m.profraw"
    #
    # protobuf
    - PROTOBUF_VERSION=3.19.3

jobs:
  include:
    - rust: stable
    - rust: nightly

cache: cargo

before_install:
  - mkdir -p $HOME/.local/bin
  - mkdir -p $HOME/.cargo/bin

install:
  - rustup component add llvm-tools-preview
  - cargo install grcov
  #
  # Installing Protobuf
  - curl -L "https://github.com/protocolbuffers/protobuf/releases/download/v$PROTOBUF_VERSION/protoc-$PROTOBUF_VERSION-linux-aarch_64.zip" -o protobuf-release.zip
  - sudo unzip protobuf-release.zip -d /usr/local
  - sudo chmod 755 /usr/local/bin/protoc
  - protoc --version
  #
  # Installing diesel console command
  - cargo install diesel_cli

before_script:
  - psql -c "create user diesel createdb password 'diesel'"
  - psql -c "create database diesel with owner diesel"
  - cd $TRAVIS_BUILD_DIR/database/diesel
  - diesel setup
  - cd $TRAVIS_BUILD_DIR

script:
  - cargo build --verbose
  - cargo test --all --verbose

after_success:
  - |
    if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then
      grcov . -s . --binary-path ./target/debug/ -t coveralls+ --llvm --branch --ignore-not-existing \
        --excl-start "#\[cfg\(test\)\]" \
        --excl-br-start "#\[cfg\(test\)\]" \
        --service-name travis-ci \
        --service-job-id $TRAVIS_JOB_ID \
        --service-pull-request $TRAVIS_PULL_REQUEST \
        --commit-sha $TRAVIS_COMMIT \
        --vcs-branch $TRAVIS_BRANCH \
        --token $COVERALLS_REPO_TOKEN > coveralls.json

      curl "https://coveralls.io/api/v1/jobs" -F json_file=@coveralls.json
    fi
