# the default dist doesn't support grcov, so ubuntu 20.4 is used.
dist: focal

language: rust

cache: cargo

services:
- postgresql

addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11

env:
  global:
  # apps deployed here to avoid `sudo`
  - PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH
  # postgresql
  - PGPORT=5433
  - PGUSER=travis
  # protobuf
  - PROTOBUF_VERSION=3.11.2

jobs:
  include:
  - rust: stable
  - rust: nightly
    env:
    - CARGO_INCREMENTAL = "0"
    - RUSTFLAGS = "-Zinstrument-coverage -Zprofile -Zpanic_abort_tests -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off"
    - RUSTDOCFLAGS = "-Cpanic=abort"

before_install:
- mkdir -p $HOME/.local/bin
- mkdir -p $HOME/.cargo/bin

install:
# Installing Protobuf
- curl -L "https://github.com/protocolbuffers/protobuf/releases/download/v$PROTOBUF_VERSION/protoc-$PROTOBUF_VERSION-linux-x86_64.zip" -o protobuf-release.zip
- sudo unzip protobuf-release.zip -d /usr/local

- rustup component add llvm-tools-preview

# Installing diesel console command
- cargo install --force diesel_cli

- cargo install --force grcov

before_script:
- psql -c "create user diesel createdb password 'diesel'"
- psql -c "create database diesel with owner diesel"
- cd $TRAVIS_BUILD_DIR/database/diesel
- diesel setup
- cd $TRAVIS_BUILD_DIR

script:
- cargo build --verbose
- cargo test --all --verbose

# move to github actions
# after_success:
#   - |
#     if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
#       grcov . -s . -t coveralls+ --llvm --branch --ignore-not-existing \
#         --excl-start "#\[test\]" \
#         --excl-br-start "#\[test\]" \
#         --service-name travis-ci \
#         --service-job-id $TRAVIS_JOB_ID \
#         --service-pull-request $TRAVIS_PULL_REQUEST \
#         --commit-sha $TRAVIS_COMMIT \
#         --vcs-branch $TRAVIS_BRANCH \
#         --token $COVERALLS_REPO_TOKEN > coveralls.json

#       curl "https://coveralls.io/api/v1/jobs" -F json_file=@coveralls.json
#     fi
