sudo: false

language: rust

cache: cargo

env:
  global:
    # install here to avoid `sudo`
    - PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH
    - PROTOBUF_VERSION=3.11.2

jobs:
  include:
    - rust: stable
    - rust: nightly
      env:
        - CARGO_INCREMENTAL=0
        - RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"

services:
  - postgresql

addons:
  apt:
    packages:

install:
  - mkdir -p $HOME/.local/bin
  - mkdir -p $HOME/.cargo/bin

  # Installing Protobuf
  - curl -L "https://github.com/protocolbuffers/protobuf/releases/download/v$PROTOBUF_VERSION/protoc-$PROTOBUF_VERSION-linux-x86_64.zip" -o protobuf-release.zip
  - sudo unzip protobuf-release.zip -d /usr/local

  # Installing diesel console command
  - cargo install --force diesel_cli

before_script:
  - psql -h localhost -U postgres -c "create user diesel createdb password 'diesel'"
  - psql -h localhost -U postgres -c "create database diesel with owner diesel"
  - cd $TRAVIS_BUILD_DIR/database/diesel
  - diesel setup
  - cd $TRAVIS_BUILD_DIR

script:
  - cargo build --verbose
  - cargo test --all --verbose

after_success:
  - |
    if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then

      curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -

      ./grcov . -s . -t coveralls+  --ignore "$HOME/.cargo/*" --ignore-not-existing --parallel \
        --service-name travis-ci \
        --service-job-number $TRAVIS_JOB_ID \
        --service-pull-request $TRAVIS_PULL_REQUEST \
        --commit-sha $TRAVIS_COMMIT \
        --vcs-branch $TRAVIS_BRANCH \
        --token $COVERALLS_REPO_TOKEN > coveralls.json

      sed -i "s%service_job_number%service_job_id%" coveralls.json
      curl "https://coveralls.io/api/v1/jobs" -F json_file=@coveralls.json

      echo 
      echo
      cat coveralls.json
      echo
      echo
      env
    fi
