sudo: false

language: rust

rust:
  - stable
  # - beta
  # - nightly

env:
  global:
    - LOCAL="~/.local"  # install here to avoid `sudo`
  matrix:
    - TEST_DIR="code-coverage"
      # PKGNAME="rust"    # must match with cargo.toml
    - TEST_DIR="syntax"
    - TEST_DIR="database/diesel"

services:
  - postgresql

addons:
  apt:
    packages:
      - binutils-dev
      - libcurl4-openssl-dev
      - zlib1g-dev
      - libdw-dev
      - libiberty-dev
      # - libelf-dev
      # - libbfd-dev    # required for `--verify`

before_install: |
  wget https://github.com/SimonKagstrom/kcov/archive/v33.tar.gz && 
      tar xzf v33.tar.gz && 
      mkdir kcov-33/build && 
      cd kcov-33/build && 
      cmake -DCMAKE_INSTALL_PREFIX:PATH=$LOCAL .. && 
      make && 
      make install && 
      cd ../..
  cargo install cargo-kcov

before_script: |
  export PATH=$LOCAL/bin:~/.cargo/bin:$PATH
  cd $TEST_DIR
  if [ "$TEST_DIR" = "database/diesel" ]; then
    psql -h localhost -U postgres -c "create user diesel createdb password 'diesel'"
    psql -h localhost -U postgres -c "create database diesel with owner diesel"
    cargo install diesel_cli
    diesel migration run
  fi

after_success: |
  cargo kcov --verbose --coveralls