sudo: false

language: rust

rust:
  - stable
  # - beta
  # - nightly

env:
  global:
    - LOCAL="~/.local"  # install here to avoid `sudo`
  matrix:
    - TEST_DIR="code-coverage"
      PKGNAME="rust"    # must match with cargo.toml
    - TEST_DIR="syntax"
    - TEST_DIR="database/diesel"

services:
  - postgresql

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - libbfd-dev    # required for `--verify`

before_script: |
  export PATH=$LOCAL/bin:~/.cargo/bin:$PATH
  cd $TEST_DIR
  if [ "$TEST_DIR" = "database/diesel" ]; then
    psql -h localhost -U postgres -c "create user diesel createdb password 'diesel'"
    psql -h localhost -U postgres -c "create database diesel with owner diesel"
    cargo install diesel_cli
    diesel migration run
  fi

after_success: |
  if [ "$TEST_DIR" = "code-coverage" ]; then
    wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz && 
      tar xzf master.tar.gz && 
      mkdir kcov-master/build && 
      cd kcov-master/build && 
      cmake -DCMAKE_INSTALL_PREFIX:PATH=$LOCAL .. && 
      make && 
      make install && 
      cd ../.. && 
      kcov --verify \
         --coveralls-id=$TRAVIS_JOB_ID \
         --exclude-pattern=/.cargo \
         target/kcov target/debug/$PKGNAME-*
  fi