sudo: false

language: rust

rust:
  - stable
  - beta
  - nightly

env:
  global:
    - LOCAL="~/.local"  # install here to avoid `sudo`
  matrix:

services:
  - postgresql

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      #- libiberty-dev # <- no such thing in Ubuntu 12.04
      - g++

before_install:
    - curl -L https://github.com/protocolbuffers/protobuf/releases/download/v$PROTOBUF_VERSION/protoc-$PROTOBUF_VERSION-linux-x86_64.zip > protoc-release.zip
    - mkdir -p $LOCAL
    - unzip protoc-release.zip -d $LOCAL
    - chmod a+x $LOCAL/bin/protoc
    - rm protoc-release.zip
    - ls $LOCAL/bin
    - ls $LOCAL/include
    - ls $LOCAL
    - protoc --version

install:
    - export PATH=$LOCAL/bin:$HOME/.cargo/bin:$PATH
    - export INCLUDE=$INCLUDE:$LOCAL/include
    - mkdir -p $LOCAL/bin
    - mkdir -p ~/.cargo/bin

    - ls $LOCAL/bin
    - which protoc
    - protoc --version

    # 1. Install kcov
    - export SRC_DIR_KCOV=~/kcov-src
    - export URL_GIT_KCOV=https://github.com/SimonKagstrom/kcov.git
    - |
        git clone $URL_GIT_KCOV $SRC_DIR_KCOV
        cd $SRC_DIR_KCOV

        # default to latest tagged version
        DEFAULT_KCOV_GIT_REF=$(git tag --list | grep "^v[0-9]\+$" | sort -V | tail --lines 1)
        KCOV_GIT_REF=${KCOV_GIT_REF:-$DEFAULT_KCOV_GIT_REF}
        git reset --hard $KCOV_GIT_REF;

        cd $SRC_DIR_KCOV && 
          mkdir build && 
          cd build && 
          cmake -DCMAKE_INSTALL_PREFIX=$LOCAL .. && 
          make && 
          make install &&
          kcov --version
    - cd $TRAVIS_BUILD_DIR

    # 2. Install cargo-kcov.
    # - cargo install cargo-kcov

before_script:
  - export RUSTFLAGS="-C link-dead-code"
  - psql -h localhost -U postgres -c "create user diesel createdb password 'diesel'"
  - psql -h localhost -U postgres -c "create database diesel with owner diesel"
  - cargo install diesel_cli
  - cd $TRAVIS_BUILD_DIR/database/diesel
  - diesel setup
  - cd $TRAVIS_BUILD_DIR

script:
  - cargo test --all

after_success: |
  ./kcov.sh  