sudo: false

language: rust

rust:
  - stable
  # - beta
  # - nightly

env:
  global:
    - LOCAL="~/.local"  # install here to avoid `sudo`
  matrix:
    # - TEST_DIR="code-coverage"
    - TEST_DIR="syntax"
    # - TEST_DIR="database/diesel"

services:
  - postgresql

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      #- libiberty-dev # <- no such thing in Ubuntu 12.04
      - g++

install:
    - export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH
    - mkdir -p ~/.cargo/bin
    - mkdir -p ~/.local/bin

    # 1. Install kcov v33.
    - export KCOV_VERSION=33
    - |
        wget https://github.com/SimonKagstrom/kcov/archive/v${KCOV_VERSION}.tar.gz &&
        tar xzf v${KCOV_VERSION}.tar.gz &&
        cd kcov-${KCOV_VERSION} &&
        mkdir build &&
        cd build &&
        cmake .. &&
        make &&
        cp src/kcov src/libkcov_sowrapper.so ~/.cargo/bin &&
        cd ../..
    - kcov --version

    # 2. Install cargo-kcov.
    - cargo install cargo-kcov

before_script:
  - export RUSTFLAGS="-C link-dead-code"
  - cd $TEST_DIR
  - |
      if [ "$TEST_DIR" = "database/diesel" ]; then
        psql -h localhost -U postgres -c "create user diesel createdb password 'diesel'"
        psql -h localhost -U postgres -c "create database diesel with owner diesel"
        cargo install diesel_cli
        diesel migration run
      fi

after_success: |
  cd ..
  kcov --verify --coveralls-id=$TRAVIS_JOB_ID \
    --include-pattern=$TEST_DIR/src \
    cov/ $TEST_DIR/target/debug/syntax-*
  # cargo kcov --verbose -- --verify --coveralls-id=$TRAVIS_JOB_ID \
  #   --exclude-pattern=/.cargo 
    