[package]
name = "log_with_env"
version = "0.1.0"
authors = ["redtankd <redtankd@qq.com>"]
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.9.0"
log4rs = "1.0.0"
slog = "2.7"
slog-term = "2.8"
slog-async = "2.7"