[package]
name = "futures"
version = "0.1.0"
authors = ["redtankd <redtankd@qq.com>"]

[lib]
name = "futures"

[dependencies]
futures = "0.1"
futures-cpupool = "0.1"
tokio-core = "0.1"
tokio-timer = "0.1"
timer = "0.1"
chrono = "0.2"