[package]
name = "server"
version = "0.1.0"
authors = ["redtankd <redtankd@qq.com>"]
edition = "2021"

[dependencies]
futures = "0.3.0"
tokio = { version = "1.13.0", features = ["full"]}
tokio-util = { version = "0.6.9", features = ["full"] }
bytes = "1.1.0"
env_logger = "0.9.0"