[package]

edition = '2018'
name = "diesel_demo"
version = "0.1.0"
authors = ["redtankd <redtankd@qq.com>"]

[dependencies]

diesel = "1.4.0"
dotenv = "0.9.0"

[features]

# multiple database support
default = ["postgres"]
postgres = ["diesel/postgres"]
mysql = ["diesel/mysql"]
