[package]
name = "diesel_demo"
version = "0.1.0"
authors = ["redtankd <redtankd@qq.com>"]

[dependencies]
diesel = "0.9.1"
diesel_codegen = { version = "0.9.0", features = ["postgres"] }
dotenv = "0.8.0"