[package]

name = "me"
version = "0.1.0"
authors = ["redtankd <redtankd@qq.com>"]
edition = "2018"

[dependencies]

futures = "0.3.1"
tokio = { version = "0.2.9", features = ["full"] }
slab = "0.4.2"

[workspace]