[package]

edition = "2018"
name = "server"
version = "0.1.0"
authors = ["redtankd <redtankd@qq.com>"]

[dependencies]

futures-preview = { version = "0.3.0-alpha.7", features = ["tokio-compat","compat"] }

tokio = { version = "0.1.0", features = ["async-await-preview"] }