cargo-features = ["edition"]

[package]
edition = "2018"
name = "tokio-async"
version = "0.1.0"
authors = ["redtankd <redtankd@qq.com>"]

[dependencies]
tokio-async-await = "0.1.0"
futures-util-preview = "0.3.0-alpha.5"