name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  PROTOBUF_VERSION: 3.11.2

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    # this job running in a docker container
    container: postgres #ubuntu

    # service containers to run with this job
    services:
      # label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Set health checks to wait until postgres has started
        # options: >-
        #   --health-cmd pg_isready
        #   --health-interval 10s
        #   --health-timeout 5s
        #   --health-retries 5

    steps:
      - uses: actions/checkout@v2
      # - uses: Harmon758/postgresql-action@v1.0.0

      - run: mkdir -p $HOME/.local/bin
      - run: mkdir -p $HOME/.cargo/bin
      - run: echo "$HOME/.local/bin:$HOME/.cargo/bin" >> $GITHUB_PATH

      - run: ping postgres
      - run: env

      # - run: cargo install grcov

      # Installing Protobuf
      # - run: curl -L "https://github.com/protocolbuffers/protobuf/releases/download/v$PROTOBUF_VERSION/protoc-$PROTOBUF_VERSION-linux-x86_64.zip" -o protobuf-release.zip
      # - run: sudo unzip protobuf-release.zip -d /usr/local

      # Initializing database
      - run: psql -h postgres -U postgres -c "create user diesel createdb password 'diesel'"
      - run: psql -h postgres -U postgres -c "create database diesel with owner diesel"
      # - run: cargo install --force diesel_cli
      # - run: cd $GITHUB_WORKSPACE/database/diesel
      # - run: diesel setup
      # - run: cd $GITHUB_WORKSPACE

      # - name: Build
        # run: cargo build --verbose
        
      # - name: Run tests
        # run: cargo test --verbose
